### ISSUE TITLE
Unredeable under dark theme

### ISSUE THREAD

**Issue by scienceisnotdead** [WeMakeMachines/joplin-plugin-event-calendar#2]
Text appears in a light grey color while the background is still yellow, making the plugin unusable.

Thanks!

PS: I take this opportunity to ask how to contribute, as I would like to implement some tweaks:

- Icons appearing alongside dates in the cell, date on top of icon
- Bigger cells
- First characters of the title always in the cell, under the date
- More than just the first two characters of the title 
- Images inside events

Thanks again

**Comment by WeMakeMachines** [comment]
Hello @scienceisnotdead, thanks for your comment! :eagle: 

I did not know about the dark theme problems - so I'll look into it. Unfortunately I'm quite busy over the next few weeks, but I'll try to find the time.

Regarding your question about contributing. You will need to know Typescript and / or CSS (for styling). If you are new to the process of contributing to a git repository, I'll outline the process here;

1) Create a fork of the repository onto your account
2) Make whatever changes you need onto your fork
3) When you're happy, push your changes to the github remote repository
4) Create a PR (pull request) from your forked repo to my repo

I will then review your changes, make my own (if needed) and push onto my master branch. I will then make a new release.

If you are new to working with the Joplin plugins, have a read of the page [Getting started with plugin development](https://joplinapp.org/api/get_started/plugins/)

Feel free to ask me questions, I'll try to reply when I can.

I'm glad of any stylistic contributions you may make, since I have a terrible eye for design!

**Comment by WeMakeMachines** [comment]
@scienceisnotdead Just looking into this - how did you enable dark theme?

**Comment by WeMakeMachines** [comment]
Closing due to lack of information
